Repository Boboiboy181/game-rental-management-server, pull requests merged in 2023-06, with the labels that each got.

#77 Fix bug finding package registeration
  src/rental-package/rental-package.service.ts
Labels: bug

#94 Make some changes in pre order module
  src/pre-order/dtos/create-pre-order.dto.ts
  src/pre-order/dtos/filter-pre-order.dto.ts
  src/pre-order/pre-order.controller.ts
  src/pre-order/pre-order.module.ts
  src/pre-order/pre-order.service.ts
  src/pre-order/schemas/pre-order.schema.ts
Labels: enhancement

#108 adding function to send confirmation email
  nest-cli.json
  package.json
  src/app.module.ts
  src/config.schema.ts
  src/pre-order/pre-order.service.ts
  src/templates/emails/pre-order-confirmation.hbs
  yarn.lock
Labels: enhancement, feature, task

#109 Voucher
  src/customer/dtos/update-customer.dto.ts
  src/invoice/dtos/create-invoice.dto.ts
  src/invoice/dtos/create-voucher.dto.ts
  src/invoice/dtos/redeem-voucher.dto.ts
  src/invoice/dtos/update-voucher.dto.ts
  src/invoice/invoice.controller.ts
  src/invoice/invoice.module.ts
  src/invoice/invoice.service.ts
  src/invoice/schemas/invoice.schema.ts
  src/invoice/schemas/voucher.schema.ts
  src/return/return.service.ts
Labels: enhancement

#112 fix getAll preorder function + delete filterdto(optional)
  src/pre-order/dtos/filter-pre-order.dto.ts
  src/pre-order/pre-order.controller.ts
  src/pre-order/pre-order.service.ts
Labels: enhancement
